name: tun_tun
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: any
  firebase_core: 2.14.0
  cloud_firestore: 4.8.2
  firebase_storage: 11.2.4
  firebase_auth: 4.6.3
  firebase_messaging: 14.6.4
  grouped_list: 5.1.2
  intl: 0.18.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icon/deaf.png
    - assets/icon/blind.png
  uses-material-design: true

